name: 'trendsphere_analytics'
version: '1.0.0'
config-version: 2

profile: 'trendsphere_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  trendsphere_analytics:
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

vars:
  'dbt_date:time_zone': 'UTC'

