name: 'Analytics'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  Analytics:
    +database: tenantapi-app-1734289077
    +schema: analytics
    staging:
      +materialized: view
      +tags: ['staging']

    intermediate:
      +materialized: table
      +tags: ['intermediate']

    marts:
      +materialized: table
      +tags: ['marts']
      fct_recent_transactions:
        +materialized: incremental
        +unique_key: order_id
        +tags: ['transactions', 'real_time']

vars:
  'dbt_date:time_zone': 'UTC'