version: 2

sources:
  - name: raw
    description: Raw data from the operational database
    database: postgres
    schema: public
    tables:
      - name: orders
        description: Raw orders data
        columns:
          - name: id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: branch_id
            description: Foreign key to branches table
          - name: customer_id
            description: Foreign key to customers table
          - name: order_total
            description: Total amount of the order
          - name: status
            description: Current status of the order
          - name: order_date
            description: Timestamp when order was placed

      - name: orderitems
        description: Raw order items data
        columns:
          - name: id
            description: Primary key of the order items table
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
          - name: product_id
            description: Foreign key to products table
          - name: quantity
            description: Quantity of the product ordered
          - name: item_total
            description: Total amount for this line item

      - name: products
        description: Raw products data
        columns:
          - name: id
            description: Primary key of the products table
            tests:
              - unique
              - not_null
          - name: branch_id
            description: Foreign key to branches table
          - name: name
            description: Name of the product
          - name: price
            description: Unit price of the product

      - name: customers
        description: Raw customers data
        columns:
          - name: id
            description: Primary key of the customers table
            tests:
              - unique
              - not_null
          - name: business_id
            description: Foreign key to businesses table
          - name: name
            description: Customer name
          - name: created_at
            description: Timestamp when customer was created
          - name: last_visit
            description: Timestamp of customer's last visit 

      - name: branches
        description: Raw branches data
        columns:
          - name: id
            description: Primary key of the branches table
            tests:
              - unique
              - not_null
          - name: business_id
            description: Foreign key to businesses table
          - name: name
            description: Branch name
          - name: city
            description: Branch city
          - name: state
            description: Branch state/province
          - name: country
            description: Branch country
          - name: created_at
            description: Creation timestamp
          - name: updated_at
            description: Last update timestamp 